---
vagrantfile-local:
    vm:
        box: ubuntu-precise-x64
        box_url: 'http://files.vagrantup.com/precise64.box'
        hostname: drupal.dev
        memory: 1024
        chosen_provider: virtualbox
        network:
            private_network: 192.168.9.10
            forwarded_port:
                5tryP4ZFTBV9:
                    host: '8888'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: default.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            svLXV9ln5L9l:
                id: webroot
                source: ./www
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
        - php-console-table
        - imagemagick
        - sendmail
        - unzip
        - mc
        - graphviz
        - memcached
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
        default_mods: false
    vhosts:
        drupal:
            servername: drupal.dev
            serveraliases:
                - www.drupal.dev
            docroot: /var/www/drupal.dev
            port: '80'
            override:
                - All
            options:
                - Indexes
                - FollowSymLinks
                - MultiViews
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''           
    modules:
        - php
        - rewrite
        - vhost_alias
    mod_pagespeed: '0'
    mod_spdy: '0'
nginx:
    install: 0
    vhosts:
        WZob4fL9trIa:
            server_name: awesome.dev
            server_aliases:
                - www.awesome.dev
            www_root: /var/www/awesome.dev
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - mcrypt
            # Uncomment the next line for PHP < 5.5, if you want to use XCache.
            # - xcache
        pear: {  }
        pecl:
            # Uncomment the next line for PHP < 5.5, if you want to use APC.
            # - apc

            # @todo At this moment XHProf can't be installed this way.
            # - xhprof
            - pecl_http
            - uploadprogress
            - apcu
    ini:
        display_errors: On
        error_reporting: '-1'
        memory_limit: 512M
        short_open_tag: Off
        session.save_path: /var/lib/php/session
        post_max_size: 2048M
        upload_max_filesize: 2048M
        error_log: /tmp/php_errors.log
    timezone: Europe/Minsk
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.max_nesting_level: 250
        xdebug.profiler_enable_trigger: '1'
        xdebug.trace_enable_trigger: '1'
drush:
    install: '1'
    settings:
        drush.tag_branch: master
mysql:
    root_password: 'drupal'
    phpmyadmin: '0'
    adminer: '1'
    databases:
        drupal:
            grant:
                - ALL
            name: drupal
            host: '%'
            user: drupal
            password: drupal
            sql_file: ''          
beanstalkd:
    install: '0'
    listenaddress: '0.0.0.0'
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: '/var/lib/beanstalkd/binlog'
    binlogfsync: 'null'
    binlogsize: '10485760'
mailcatcher:
    install: '1'
    settings:
        http_ip: 0.0.0.0
        http_port: 8088
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        mailcatcher_path: /usr/local/rvm/bin        
rabbitmq:
    install: '0'
    settings:
        port: '5672'
samba_server:
    install: '1'
apcu:
    install: '1'
php_memcached:
    install: '1'
mariadb:
    install: '0'
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
solr:
    install: '0'
php_xhprof:
    install: '1'
pimpmylog:
    install: '0'
experimental: 
    install: '1'
varnish:
    install: '0'
    settings:
        http_port: 8080
        storage_size: 0.5G
webgrind:
    install: '0'
    domain: 'webgrind.drupal.dev'
